fix(package.json: Move ESLint related dependencies to peerDependencies section
smrwsky/code-style pull request #24
Opened 2023-10-17 18:55 UTC by Labriko

## Description

This fix resolves compatibility issues with library consumers.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-10-17 19:50 UTC, smrwsky requested changes

2023-10-17 19:50 UTC, smrwsky commented on package.json
> +  "peerDependencies": {
Peer dependencies should be duplicated in dev dependencies so they can be installed locally.

2023-10-17 19:50 UTC, smrwsky commented on package.json
> +    "prettier": "^2.8.4",
This package also provides prettier config for external usage. Shouldn't it be added in peer dependencies as well?

2023-10-17 19:52 UTC, smrwsky commented
Also please run changeset command and set patch update, then it will be published in npm.

2023-10-18 10:17 UTC, Labriko commented on package.json
> +  "peerDependencies": {
Agree, fixed

2023-10-18 10:26 UTC, Labriko commented on package.json
> +    "prettier": "^2.8.4",
Done

2023-10-20 14:00 UTC, smrwsky requested changes

2023-10-26 19:56 UTC, Labriko commented on package.json
> +  "version": "0.2.0",
Got it, thanks. Is it ok now?

2023-11-01 16:55 UTC, mvshvssv approved these changes

2023-11-01 16:56 UTC, merged